book:
  service:
    url: ${BOOK_SERVICE_URL:http://localhost:9002}
employee:
  service:
    url: ${EMPLOYEE_SERVICE_URL:http://localhost:9001}
user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:9004}